workflows:
  pingpong-build:
    name: PingPong Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build
        script: |
          xcodebuild \
            -scheme PingPong \
            -workspace PingPong.xcworkspace \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build
      
      - name: Copy .app
        script: |
          mkdir -p build/app
          cp -r ./build/Build/Products/Debug-iphoneos/PingPong.app ./build/app/
    artifacts:
      - ./build/app/PingPong.app
